INSERT INTO TYPE_SIROP (nom) VALUES ('Ambré')
INSERT INTO TYPE_SIROP (nom) VALUES ('Clair')
INSERT INTO TYPE_SIROP (nom) VALUES ('Foncé')
INSERT INTO PRODUIT (nom,type_sirop_id,description,contenance,prix,image_url) VALUES ('Produit 1',1,'Description produit 1','500 mL',10,null)
INSERT INTO PRODUIT (nom,type_sirop_id,description,contenance,prix,image_url) VALUES ('Produit 1 Grand',1,'Description produit 1 Grand','1500 mL',15,null)
INSERT INTO PRODUIT (nom,type_sirop_id,description,contenance,prix,image_url) VALUES ('Produit 2',2,'Description produit 2','500 mL',10,null)
INSERT INTO PRODUIT (nom,type_sirop_id,description,contenance,prix,image_url) VALUES ('Produit 2 Grand',2,'Description produit 2 Grand','1500 mL',15,null)
INSERT INTO PRODUIT (nom,type_sirop_id,description,contenance,prix,image_url) VALUES ('Produit 3',3,'Description produit 3','500 mL',10,null)
INSERT INTO PRODUIT (nom,type_sirop_id,description,contenance,prix,image_url) VALUES ('Produit 3 Grand',3,'Description produit 3 Grand','1500 mL',15,null)
INSERT INTO STATUT_COMMANDE (nom) VALUES ('En cours')
INSERT INTO STATUT_COMMANDE (nom) VALUES ('Valide')

INSERT INTO COMMANDE (statut_commande_id) VALUES (2)
INSERT INTO LIGNE_COMMANDE(prix_unitaire,quantite,commande_id,produit_id) VALUES (15.0,2,1,2)
INSERT INTO LIGNE_COMMANDE(prix_unitaire,quantite,commande_id,produit_id) VALUES (10.0,1,1,1)
INSERT INTO LIGNE_COMMANDE(prix_unitaire,quantite,commande_id,produit_id) VALUES (10.0,3,1,3)

INSERT INTO COMMANDE (statut_commande_id) VALUES (1)
INSERT INTO LIGNE_COMMANDE(prix_unitaire,quantite,commande_id,produit_id) VALUES (15.0,2,1,2)